### ISSUE TITLE
Job Tracker V3 Milestone 1

### ISSUE THREAD

**Issue by KyleHu14** [KyleHu14/job-tracker#13]
Milestone 1 will be the laying the basic foundations of the web app

Backend : 
- [x] Write SQL for supabase
- [x] Plan a nodejs backend rest api 

Frontend : 
- [x] Layout foundations for the table component
  - [x] Edit columns.tsx
  - [x] Edit data-table.tsx
